src/Entity/Tuteur.php
<?php

namespace App\Entity;

use App\Repository\TuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TuteurRepository::class)]
class Tuteur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    private $name_father;

    #[ORM\Column(type: 'string', length: 255)]
    private $name_mather;

    #[ORM\Column(type: 'string', length: 255)]
     #[Assert\NotBlank]
    private $telephone_father;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $telephone_mother;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    private $email;

    #[ORM\Column(type: 'string', length: 255)]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    private $adresse;

    #[ORM\Column(type: 'string', length: 255)]
    private $city;

    // #[ORM\OneToMany(mappedBy: 'tuteur', targetEntity: Student::class, cascade:"persist")]
    // #[Assert\Count(min:1)]
    // #[Assert\Valid]
    /**
     * Undocumented variable
     * @var Collection<int, student>
     * @ORM\OneToMany(targetEntity=student::class, mappedBy="tuteur", orphanRemoval=true, cascade={"persist"})
     * @author Hamza
     * @version 1.0
     */
    private Collection $students;

    // #[ORM\OneToMany(mappedBy: 'tuteur', targetEntity: Eleve::class)]
    /**
     * @var Collection<int, Eleve>
     * @ORM\OneToMany(targetEntity=Eleve::class, mappedBy="tuteur", orphanRemoval=true, cascade={"persist"})
     */
    private $eleves;

    public function __construct()
    {
        $this->students = new ArrayCollection();
        $this->eleves = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameFather(): ?string
    {
        return $this->name_father;
    }

    public function setNameFather(string $name_father): self
    {
        $this->name_father = $name_father;

        return $this;
    }

    public function getNameMather(): ?string
    {
        return $this->name_mather;
    }

    public function setNameMather(string $name_mather): self
    {
        $this->name_mather = $name_mather;

        return $this;
    }

    public function getTelephoneFather(): ?string
    {
        return $this->telephone_father;
    }

    public function setTelephoneFather(string $telephone_father): self
    {
        $this->telephone_father = $telephone_father;

        return $this;
    }

    public function getTelephoneMother(): ?string
    {
        return $this->telephone_mother;
    }

    public function setTelephoneMother(?string $telephone_mother): self
    {
        $this->telephone_mother = $telephone_mother;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }


    public function getStudents(): Collection
    {
        return $this->students;
    }

    public function addStudent(Student $student): self
    {
        if (!$this->students->contains($student)) {
            $this->students->add($student);
            $student->setTuteur($this);
        }

        return $this;
    }

    public function removeStudent(Student $student): self
    {
        if ($this->students->removeElement($student)) {
            // set the owning side to null (unless already changed)
            if ($student->getTuteur() === $this) {
                $student->setTuteur(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
         return (string) $this->getEmail();
    }

    /**
     * @return Collection|Eleve[]
     */
    public function getEleves(): Collection
    {
        return $this->eleves;
    }

    public function addEleve(Eleve $eleve): self
    {
        if (!$this->eleves->contains($eleve)) {
            $this->eleves->add($eleve) ;
            $eleve->setTuteur($this);
        }

        return $this;
    }

    public function removeEleve(Eleve $eleve): self
    {
        if ($this->eleves->removeElement($eleve)) {
            // set the owning side to null (unless already changed)
            if ($eleve->getTuteur() === $this) {
                $eleve->setTuteur(null);
            }
        }

        return $this;
    }

}

src/Form/TuteurType.php
<?php

namespace App\Form;

use App\Entity\Tuteur;
use App\Entity\Student;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use App\Form\StudentType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class TuteurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name_father', TextType::class, [
                    'help' => 'The father name is important.',
                    ])
            ->add('name_mather', TextType::class)
            ->add('telephone_father', TextType::class)
            ->add('telephone_mother', TextType::class)
            ->add('email', EmailType::class)
            ->add('password', PasswordType::class)
            ->add('adresse', TextType::class)
            ->add('city', TextType::class)
            ->add('students', CollectionType::class, [
                'entry_type' => StudentType::class,
                'by_reference' => false,
                'allow_add' => true,
                'allow_delete' => true,
                'attr' => ['class' => 'fieldset-student'],
                'error_bubbling' => false

                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tuteur::class,
        ]);
    }
}

src/Controller/TuteurController.php
<?php

namespace App\Controller;

use App\Entity\Tuteur;
use App\Form\TuteurType;
use App\Repository\TuteurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/tuteur')]
class TuteurController extends AbstractController
{
    /**
     * display all parents of students
     * @param  \App\Repository\TuteurRepository           $tuteurRepository
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @author Hamza
     * @version 1.0
     */
    #[Route('/', name: 'tuteur_index', methods: ['GET'])]
    public function index(TuteurRepository $tuteurRepository): Response
    {
        return $this->render('tuteur/index.html.twig', [
            'tuteurs' => $tuteurRepository->findAll(),
        ]);
    }

/**
 * Create new parents
 * @param  \Symfony\Component\HttpFoundation\Request  $request
 * @param  \Doctrine\ORM\EntityManagerInterface       $entityManager
 *
 * @return \Symfony\Component\HttpFoundation\Response
 * @author Hamza
 * @version 1.0
 */
    #[Route('/new', name: 'tuteur_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $tuteur = new Tuteur();
        $form = $this->createForm(TuteurType::class, $tuteur);
        $form->handleRequest($request);
// dd($tuteur);
        if ($form->isSubmitted() && $form->isValid()) {

            // $students = $tuteur->getStudents();
            // foreach($students as $student){

            // $entityManager->persist($student);

            // }

            $entityManager->persist($tuteur);
            $entityManager->flush();

            return $this->redirectToRoute('tuteur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('tuteur/new.html.twig', [
            // 'tuteur' => $tuteur,
            'form' => $form,
        ]);
    }

     /**
     * Undocumented function
     * @param  \App\Entity\Tuteur                         $tuteur
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @author Hamza
     * @version 1.0
     */
    #[Route('/{id}', name: 'tuteur_show', methods: ['GET'])]
    public function show(Tuteur $tuteur): Response
    {
        return $this->render('tuteur/show.html.twig', [
            'tuteur' => $tuteur,
        ]);
    }

    #[Route('/{id}/edit', name: 'tuteur_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Tuteur $tuteur, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TuteurType::class, $tuteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('tuteur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('tuteur/edit.html.twig', [
            'tuteur' => $tuteur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'tuteur_delete', methods: ['POST'])]
    public function delete(Request $request, Tuteur $tuteur, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tuteur->getId(), $request->request->get('_token'))) {
            $entityManager->remove($tuteur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('tuteur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/tuteur/_delete_form.html.twig
<form method="post" action="{{ path('tuteur_delete', {'id': tuteur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tuteur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/tuteur/_form.html.twig
{{ form_start(form) }}

    {{ form_errors(form.students)}}

    {{ form_row(form.name_father)}}
    {{ form_row(form.name_mather)}}
    {{ form_row(form.telephone_father)}}
    {{ form_row(form.telephone_mother)}}
    {{ form_row(form.email)}}
    {{ form_row(form.password)}}
    {{ form_row(form.adresse)}}
    {{ form_row(form.city)}}

    <button:button class="btn btn-primary btn-new"
        id="new-student"
        data-collection=#students
        >New Student</button:button>

    <div id="students" class="row"
        data-prototype="{{ include("tuteur/_student.html.twig", {form: form.students.vars.prototype})|e("html_attr")}}"
        data-index="{{form.students|length > 0 ? form.students|last.vars.name +1 : 0}} ">

        {% for student in form.students  %}
        <div class="col-4">
            {{ include("tuteur/_student.html.twig", {form: student} )}}
        </div>
        {% endfor %}

    </div>

  {# <button type="button" class="btn btn-primary" id="new-student">Ajouter Enfant (student)</button> #}


    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form)}}

templates/tuteur/_student.html.twig
<div class="col-4 item">
    {{ form_row(form.name) }}
    {{ form_row(form.surname) }}
    {{ form_row(form.date_naissance) }}
    {{ form_row(form.photo) }}
    {{ form_row(form.sexe) }}
    {{ form_row(form.info_perso) }}

    <div class="form-group">
        <button type="button" class="btn btn-danger btn-remove">Remove</button:button>
    </div>
</div>

templates/tuteur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tuteur{% endblock %}

{% block body %}
    <h1>Edit Tuteur</h1>

    {{ include('tuteur/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('tuteur_index') }}">back to list</a>

    {{ include('tuteur/_delete_form.html.twig') }}
{% endblock %}

templates/tuteur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tuteur index{% endblock %}

{% block body %}
    <h1>Tuteur index</h1>

    <table class="table">
        <thead>
            <tr>
                <th class="text-center">Id</th>
                <th class="text-center">Name_father</th>
                <th class="text-center">Name_mather</th>
                <th class="text-center">Telephone_father</th>
                <th class="text-center">Telephone_mother</th>
                <th class="text-center">Email</th>
                <th class="text-center">Password</th>
                <th class="text-center">Adresse</th>
                <th class="text-center">City</th>
                <th class="text-center">actions</th>
            </tr>
        </thead>
        <tbody>
        {% for tuteur in tuteurs %}
            <tr>
                <td>{{ tuteur.id }}</td>
                <td>{{ tuteur.nameFather }}</td>
                <td>{{ tuteur.nameMather }}</td>
                <td>{{ tuteur.telephoneFather }}</td>
                <td>{{ tuteur.telephoneMother }}</td>
                <td>{{ tuteur.email }}</td>
                <td>{{ tuteur.password }}</td>
                <td>{{ tuteur.adresse }}</td>
                <td>{{ tuteur.city }}</td>
                <td>
                    <a href="{{ path('tuteur_show', {'id': tuteur.id}) }}">show</a>
                    <a href="{{ path('tuteur_edit', {'id': tuteur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('tuteur_new') }}">Create new</a>
{% endblock %}

templates/tuteur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tuteur{% endblock %}

{% block body %}
    <h1>Create new Tuteur</h1>

    {{ include('tuteur/_form.html.twig') }}

    <a href="{{ path('tuteur_index') }}">back to list</a>
{% endblock %}

templates/tuteur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tuteur{% endblock %}

{% block body %}
    <h1>Tuteur</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ tuteur.id }}</td>
            </tr>
            <tr>
                <th>Name_father</th>
                <td>{{ tuteur.nameFather }}</td>
            </tr>
            <tr>
                <th>Name_mather</th>
                <td>{{ tuteur.nameMather }}</td>
            </tr>
            <tr>
                <th>Telephone_father</th>
                <td>{{ tuteur.telephoneFather }}</td>
            </tr>
            <tr>
                <th>Telephone_mother</th>
                <td>{{ tuteur.telephoneMother }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ tuteur.email }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ tuteur.password }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ tuteur.adresse }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ tuteur.city }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('tuteur_index') }}">back to list</a>

    <a href="{{ path('tuteur_edit', {'id': tuteur.id}) }}">edit</a>

    {{ include('tuteur/_delete_form.html.twig') }}
{% endblock %}